### PR TITLE
VEOSS-1395 | Update content on rejection reason pages. Auto update of…

### PR DESCRIPTION
**Pull request by warrenskiwork1979**
… copyright year.

### CODE REVIEW

**Comment by warrenskiwork1979** [comment]
Test this again please

**Comment by warrenskiwork1979** [comment]
test again please

**Comment by warrenskiwork1979** [comment]
test again

**Comment by warrenskiwork1979** [comment]
retest this please

**Review by DevAndyroo — APPROVED** [review]

**Pull request merged**
